#!/bin/bash

export RELEASE_NAME=nifi
export RELEASE_NAMESPACE=default
export CHART_PATH=.
export PROXY_HOST=nifi-on-gke
export ADMIN_CN=nifi-gke

export VALUES_FILES="-f values-gke.yaml -f values-lowdisk.yaml -f values-minzookeeper.yaml"
