apiVersion: v1
kind: Service
metadata:
    name: {{ template "apache-nifi.fullname" . }}-headless
    labels:
        app: {{ include "apache-nifi.name" . | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
spec:
    ports:
    - port: {{ .Values.properties.httpPort }}
      name: http
    - port: {{ .Values.properties.clusterPort }}
      name: cluster
    clusterIP: None
    selector:
        app: {{ include "apache-nifi.name" . | quote }}
        release: {{ .Release.Name | quote }}
